import { Event } from '@/types/event';

export const mockEvents: Event[] = [
  {
    id: 1,
    title: 'Tech Conference 2025',
    description: 'Annual tech conference on AI and ML trends shaping the industry.',
    date: '2025-05-15T10:00:00Z',
    category: 'Conference',
    status: 'Planned',
    isFavorite: false,
  },
  {
    id: 2,
    title: 'Team Meetup',
    description: 'Monthly team sync to align on goals and review progress.',
    date: '2025-06-30T14:00:00Z',
    category: 'Meeting',
    status: 'Planned',
    isFavorite: false,
  },
  {
    id: 3,
    title: 'React Advanced Webinar',
    description: 'Deep dive into React Server Components and the App Router.',
    date: '2025-04-20T18:00:00Z',
    category: 'Webinar',
    status: 'Completed',
    isFavorite: true,
  },
  {
    id: 4,
    title: 'Design System Workshop',
    description: 'Hands-on session building a scalable component library.',
    date: '2025-07-10T09:00:00Z',
    category: 'Conference',
    status: 'Planned',
    isFavorite: true,
  },
  {
    id: 5,
    title: 'Q2 Planning Meeting',
    description: 'Quarterly roadmap review with stakeholders.',
    date: '2025-04-02T11:00:00Z',
    category: 'Meeting',
    status: 'Completed',
    isFavorite: false,
  },
  {
    id: 6,
    title: 'TypeScript Best Practices',
    description: 'Webinar covering advanced TypeScript patterns for large codebases.',
    date: '2025-05-28T16:00:00Z',
    category: 'Webinar',
    status: 'Planned',
    isFavorite: false,
  },
  {
    id: 7,
    title: 'Frontend Performance Summit',
    description: 'Conference sessions on Core Web Vitals, bundling, and edge rendering.',
    date: '2025-08-05T09:30:00Z',
    category: 'Conference',
    status: 'Planned',
    isFavorite: true,
  },
];
